name: example

on:
  pull_request:
    branches:
      - main
    paths:
      - test.txt
    types:
      - opened
      - synchronize
  pull_request_review:
    types:
      - submitted

jobs:
  example:
    name: example
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "this workflow ran"
